In [26]:
import requests
import pandas as pd

1. get list of exercise

- sort excercise by type
- define rules to group exercise by type of training-
- define rules to match exercerise together

2. ask users question
- experience
- goal
- nb of days
- access to materials

In [90]:
url = "https://wger.de/api/v2/exercisebaseinfo/?language=2&limit=2000"
data = requests.get(url)

In [92]:
len(df_exercise)

316

In [93]:
all_exercise = data.json()
df_muscle = pd.DataFrame(data = all_exercise['results'])
df_muscle.to_csv('list_exerciseBase.csv')

## -----

3. create api that requests data

In [96]:
df_base = pd.read_csv('list_exerciseBase.csv',index_col=0)
df_base.head()

,id,uuid,category,muscles,muscles_secondary,equipment,license,license_author,images,exercises,variations
0,9,1b020b3a-3732-4c7e-92fd-a0cec90ed69b,"{'id': 10, 'name': 'Abs'}",[],[],"[{'id': 10, 'name': 'Kettlebell'}]","{'id': 2, 'full_name': 'Creative Commons Attri...",deusinvictus,[],"[{'id': 345, 'uuid': 'c788d643-150a-4ac7-97ef-...",NaN
1,12,53906cd1-61f1-4d56-ac60-e4fcc5824861,"{'id': 9, 'name': 'Legs'}","[{'id': 8, 'name': 'Gluteus maximus', 'is_fron...","[{'id': 11, 'name': 'Biceps femoris', 'is_fron...",[],"{'id': 1, 'full_name': ' Creative Commons Attr...",flori,[],"[{'id': 174, 'uuid': '99881bdd-43d7-4c3b-82ed-...",NaN
2,13,49859097-644a-417a-8cb7-491b7d8bc383,"{'id': 9, 'name': 'Legs'}",[],[],[],"{'id': 1, 'full_name': ' Creative Commons Attr...",Marius,[],"[{'id': 223, 'uuid': 'e56d0a17-b1b8-427d-991e-...",NaN
3,20,f24cb758-9c0d-42d4-ad9e-6025c527dd13,"{'id': 13, 'name': 'Shoulders'}",[],[],"[{'id': 3, 'name': 'Dumbbell'}]","{'id': 1, 'full_name': ' Creative Commons Attr...",trzr23,[],"[{'id': 228, 'uuid': '880bff63-6798-4ffc-a818-...",5.0
4,22,80d6017d-58a1-4061-8fa2-0d08b9886523,"{'id': 9, 'name': 'Legs'}","[{'id': 10, 'name': 'Quadriceps femoris', 'is_...","[{'id': 8, 'name': 'Gluteus maximus', 'is_fron...",[],"{'id': 2, 'full_name': 'Creative Commons Attri...",Tetsuhiko Asai,[],"[{'id': 353, 'uuid': '583281c7-2362-48e7-95d5-...",NaN

In [68]:
df_muscle = pd.read_csv('list_muscles.csv',index_col=0)
df_muscle.head()

,id,name,is_front,image_url_main,image_url_secondary
0,2,Anterior deltoid,True,/static/images/muscles/main/muscle-2.svg,/static/images/muscles/secondary/muscle-2.svg
1,1,Biceps brachii,True,/static/images/muscles/main/muscle-1.svg,/static/images/muscles/secondary/muscle-1.svg
2,11,Biceps femoris,False,/static/images/muscles/main/muscle-11.svg,/static/images/muscles/secondary/muscle-11.svg
3,13,Brachialis,True,/static/images/muscles/main/muscle-13.svg,/static/images/muscles/secondary/muscle-13.svg
4,7,Gastrocnemius,False,/static/images/muscles/main/muscle-7.svg,/static/images/muscles/secondary/muscle-7.svg

In [77]:
df_exercise = pd.read_csv('list_exercises.csv',index_col=0)
df_exercise.set_index('id',inplace=True)
df_exercise.head()

,uuid,name,exercise_base,status,description,creation_date,category,muscles,muscles_secondary,equipment,language,license,license_author,variations
id,,,,,,,,,,,,,,
345,c788d643-150a-4ac7-97ef-84643c6419bf,2 Handed Kettlebell Swing,9,2,<p>Two Handed Russian Style Kettlebell swing</p>,2015-08-03,10,[],[],[10],2,2,deusinvictus,[]
227,53ca25b3-61d9-4f72-bfdb-492b83484ff5,Arnold Shoulder Press,20,2,<p>Very common shoulder exercise.</p>\n<p> </p...,2014-03-09,13,[],[],[3],2,1,trzr23,"[227, 329, 229, 190, 119, 123, 152, 155]"
289,6add5973-86d0-4543-928a-6bb8b3f34efc,Axe Hold,31,2,<p>Grab dumbbells and extend arms to side and ...,2014-11-02,8,[],[],[3],2,1,GrosseHund,[]
637,0fd6154d-fb53-4b24-acc0-1c5c05b57ebc,Back Squat,34,2,<p>Place a barbell in a rack just below should...,2019-05-29,9,[],[],[],2,2,axel,[]
343,1b9dc5bc-790b-4e21-a55d-f8b3115e94c5,Barbell Ab Rollout,41,2,<p>Place a barbell on the floor at your feet.<...,2015-07-27,10,[14],[],[1],2,2,sevae,[]

In [81]:
df_exercise[df_exercise['name'] == 'Bench Press']

,uuid,name,exercise_base,status,description,creation_date,category,muscles,muscles_secondary,equipment,language,license,license_author,variations
id,,,,,,,,,,,,,,
192,5da6340b-22ec-4c1b-a443-eef2f59f92f0,Bench Press,73,2,"<p>Lay down on a bench, the bar should be dire...",2013-08-11,11,[4],"[2, 5]","[1, 8]",2,1,sistab2,"[192, 100, 101, 163, 210, 211, 270, 399]"

In [83]:
df_exercise.loc[192]

uuid                              5da6340b-22ec-4c1b-a443-eef2f59f92f0
name                                                       Bench Press
exercise_base                                                       73
status                                                               2
description          <p>Lay down on a bench, the bar should be dire...
creation_date                                               2013-08-11
category                                                            11
muscles                                                            [4]
muscles_secondary                                               [2, 5]
equipment                                                       [1, 8]
language                                                             2
license                                                              1
license_author                                                 sistab2
variations                    [192, 100, 101, 163, 210, 211, 270, 399]
Name: 192, dtype: object

In [89]:
df_image[df_image.exercise_base == 73]

,uuid,exercise_base,image,is_main,status,style
id,,,,,,
68,08517378-bc36-4f6b-9952-1f45a02d936e,73,https://wger.de/media/exercise-images/192/Benc...,True,2,1
70,41e5c58e-0325-4620-8d96-7372cc4dae8c,73,https://wger.de/media/exercise-images/192/Benc...,False,2,1

In [74]:
df_image = pd.read_csv('list_images.csv',index_col=0)
df_image.set_index('id',inplace=True)
df_image.head()

,uuid,exercise_base,image,is_main,status,style
id,,,,,,
3,ef0b00e2-3323-4e7f-88fe-d71ef34b3384,167,https://wger.de/media/exercise-images/91/Crunc...,True,2,1
7,bed4f21b-28be-4ef1-bd88-1a4e3db66c5c,427,https://wger.de/media/exercise-images/93/Decli...,True,2,1
11,59efcec2-a7ce-40ba-bf2b-1a6eabe52fbd,301,https://wger.de/media/exercise-images/128/Hype...,True,2,1
15,1c37e4e1-5144-4a50-8294-16180a9bc767,76,https://wger.de/media/exercise-images/88/Narro...,True,2,1
19,065f9418-6245-46ae-8e24-b4013ce084e4,95,https://wger.de/media/exercise-images/129/Stan...,True,2,1

In [76]:
df_image.loc[227].image

KeyError: 227